spring.application.name=course-enroll-api
logging.level.com.yourcompany.springbootmall=DEBUG

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false
spring.datasource.username=
spring.datasource.password=

spring.config.import=optional:classpath:application-db.properties